/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/3D/hrRaum.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fläche.geometry}
        material={materials["Material.004"]}
        position={[-0.4, -2.01, -0.92]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fläche003.geometry}
        material={nodes.Fläche003.material}
        position={[-0.39, 1.14, 2.57]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel001.geometry}
        material={nodes.Würfel001.material}
        position={[-2.38, -1.44, -0.53]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel014_Würfel030.geometry}
        material={nodes.Würfel014_Würfel030.material}
        position={[-1.84, -1.1, 1.82]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel016_Würfel032.geometry}
        material={nodes.Würfel016_Würfel032.material}
        position={[-1.84, -0.87, 2.02]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel017_Würfel033.geometry}
        material={nodes.Würfel017_Würfel033.material}
        position={[1.55, -0.9, -0.46]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel022_Würfel038.geometry}
        material={nodes.Würfel022_Würfel038.material}
        position={[0.75, -0.92, -0.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Zylinder.geometry}
        material={nodes.Zylinder.material}
        position={[0.56, -1.37, 1.83]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kegel003.geometry}
        material={materials["Material.001"]}
        position={[0.56, 0.71, 1.83]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel002_Würfel047.geometry}
        material={nodes.Würfel002_Würfel047.material}
        position={[-4.97, -1.1, -0.07]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel003_Würfel048.geometry}
        material={nodes.Würfel003_Würfel048.material}
        position={[-5.17, -0.87, -0.07]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel005_Würfel050.geometry}
        material={nodes.Würfel005_Würfel050.material}
        position={[3.61, -0.81, 2.15]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel006_Würfel056.geometry}
        material={nodes.Würfel006_Würfel056.material}
        position={[-1.23, 0.24, -4.23]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel004_Würfel058.geometry}
        material={nodes.Würfel004_Würfel058.material}
        position={[4.18, -1.04, -3.98]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel007_Würfel059.geometry}
        material={materials["Material.007"]}
        position={[-5, -0.84, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel009_Würfel060.geometry}
        material={nodes.Würfel009_Würfel060.material}
        position={[4.16, 0.28, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel010_Würfel061.geometry}
        material={materials["Material.006"]}
        position={[4.87, 1.88, -1.09]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel011_Würfel066.geometry}
        material={nodes.Würfel011_Würfel066.material}
        position={[-1.43, 2.59, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel015_Würfel070.geometry}
        material={nodes.Würfel015_Würfel070.material}
        position={[-0.81, 2.57, 2.37]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel033_Würfel080.geometry}
        material={materials["Material.009"]}
        position={[-0.8, 2.53, 2.37]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel013_Würfel083.geometry}
        material={nodes.Würfel013_Würfel083.material}
        position={[-1.43, 2.59, -3.99]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.unamed_unamedmesh.geometry}
        material={nodes.unamed_unamedmesh.material}
        position={[3.96, -0.29, 0.8]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.unamed001_unamedmesh001.geometry}
        material={nodes.unamed001_unamedmesh001.material}
        position={[-4.23, -0.6, 0.51]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel042_Würfel102.geometry}
        material={nodes.Würfel042_Würfel102.material}
        position={[1.53, 0.03, 0.43]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel043_Würfel103.geometry}
        material={nodes.Würfel043_Würfel103.material}
        position={[1.53, 0.03, -1.27]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel044_Würfel105.geometry}
        material={nodes.Würfel044_Würfel105.material}
        position={[1.56, -0.16, -0.45]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel045_Würfel106.geometry}
        material={nodes.Würfel045_Würfel106.material}
        position={[1.54, -0.14, -2.06]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Würfel046_Würfel107.geometry}
        material={nodes.Würfel046_Würfel107.material}
        position={[1.54, -0.14, 1.17]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/hrRaum.glb");
